// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaubsaaeexjdgzpzuqcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdWJzYWFlZXhqZGd6cHp1cWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzOTUwMTQsImV4cCI6MjA1Mzk3MTAxNH0.SBOAxBIGbaVRxmYo_ms5pfAKXpfBw2K8snPaa5T0ms8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);